{
    "code": 1,
    "reason": "进入房间成功！",
    "deskConfig": {
        "gameId": 1003130,
        "gameName": "robot哥陪打房",
        "gameNameTW": "",
        "gameNameCN": "",
        "matchType": 800,
        "subGameType": "",
        "matchID": 0,
        "baseScore": 1,
        "beforeScore": 1,
        "playTimes": 0,
        "playerCount": 9,
        "minTake": 3,
        "maxTake": 10000,
        "hostId": "",
        "ownerControl": false,
        "isGameStart": false,
        "roomStatus": 2,
        "isStraddle": false,
        "isInsurance": false,
        "ipNotify": false,
        "gpsNotify": false,
        "isShortCard": false,
        "minHoldMultiple": 0,
        "currencyType": 3,
        "tableId": 0,
        "isLive": false,
        "roomType": 3,
        "delayCount": 0,
        "pauseCount": 0,
        "pauseTimeCut": 0,
        "isReplay": false,
        "replayState": false,
        "replayTimeCut": 0,
        "tableMicroIsOpen": false,
        "isCoinQuick": true,
        "coinQuickLevel": 193,
        "enableTimeBank": 1,
        "handCount": 0,
        "mode": "",
        "playerCountForSNG": 0
    },
    "deskInfo": {
        "userList": [
            {
                "userInfo": {
                    "comId": "JOY",
                    "userId": "1739154",
                    "userName": "+852 184644",
                    "nickname": "aa1800",
                    "gender": 1,
                    "signiture": "",
                    "photoUrl": "3",
                    "ip": "172.70.223.252",
                    "jingDu": 200,
                    "weiDu": 200,
                    "score": 213,
                    "idType": 0,
                    "isOpenMic": false,
                    "matchInfo": {
                        "gameTimes": 0,
                        "playTimes": 0,
                        "vPIP": 0,
                        "winRate": 0
                    },
                    "poolRate": "16.55%",
                    "country": "",
                    "Level": 9,
                    "TaxSetting": 0,
                    "TaxDefault": 0,
                    "Uid0": "99999999",
                    "Uid1": "99999998",
                    "Uid2": "99999997",
                    "Uid3": "",
                    "Uid4": "",
                    "Uid5": "",
                    "Uid6": "",
                    "Uid7": "",
                    "Uid8": "",
                    "Uid9": "",
                    "TaxSetting0": 100,
                    "TaxSetting1": 100,
                    "TaxSetting2": 90,
                    "TaxSetting3": 0,
                    "TaxSetting4": 0,
                    "TaxSetting5": 0,
                    "TaxSetting6": 0,
                    "TaxSetting7": 0,
                    "TaxSetting8": 0,
                    "TaxSetting9": 0,
                    "Tax0": 0,
                    "Tax1": 10,
                    "Tax2": 90,
                    "Tax3": 0,
                    "Tax4": 0,
                    "Tax5": 0,
                    "Tax6": 0,
                    "Tax7": 0,
                    "Tax8": 0,
                    "Tax9": 0,
                    "Parent": "99999997",
                    "VipLevel": 0,
                    "RakebackPercent": 0,
                    "killCount": 0,
                    "bounty": 0,
                    "bonus": 0
                },
                "tableScore": 0,
                "totalScore": 0,
                "isPlaying": false,
                "isGiveUp": false,
                "isAllIn": false,
                "pos": 0,
                "take": 3,
                "status": 3,
                "cards": [],
                "cardType": 0,
                "operateCard": 0,
                "maxCards": [],
                "isHaveCards": true,
                "showCards": [
                    0,
                    0
                ],
                "delayTimes": 0,
                "straddleNextCnt": -1,
                "isLeave": false,
                "isFocus": false,
                "isOpenMic": false,
                "turnLeftSeconds": 0,
                "mttUseDelay": false,
                "mttDelaySecond": 0,
                "nlhDelaySpend": 0,
                "payForGetCardType": 0,
                "squidCount": 0,
                "minTake": 0,
                "maxTake": 0,
                "isOriginTake": false,
                "handPlayerTurnedFlag": false,
                "nextGameLeaveFlag": false,
                "foldToStandUpFlag": false
            },
            {
                "userInfo": {
                    "comId": "JOY",
                    "userId": "1739162",
                    "userName": "+852 168254",
                    "nickname": "aa1801",
                    "gender": 1,
                    "signiture": "",
                    "photoUrl": "3",
                    "ip": "172.69.63.138",
                    "jingDu": 200,
                    "weiDu": 200,
                    "score": 2145.5,
                    "idType": 0,
                    "isOpenMic": false,
                    "matchInfo": {
                        "gameTimes": 0,
                        "playTimes": 0,
                        "vPIP": 0,
                        "winRate": 0
                    },
                    "poolRate": "17.65%",
                    "country": "",
                    "Level": 9,
                    "TaxSetting": 0,
                    "TaxDefault": 0,
                    "Uid0": "99999999",
                    "Uid1": "99999998",
                    "Uid2": "99999997",
                    "Uid3": "",
                    "Uid4": "",
                    "Uid5": "",
                    "Uid6": "",
                    "Uid7": "",
                    "Uid8": "",
                    "Uid9": "",
                    "TaxSetting0": 100,
                    "TaxSetting1": 100,
                    "TaxSetting2": 90,
                    "TaxSetting3": 0,
                    "TaxSetting4": 0,
                    "TaxSetting5": 0,
                    "TaxSetting6": 0,
                    "TaxSetting7": 0,
                    "TaxSetting8": 0,
                    "TaxSetting9": 0,
                    "Tax0": 0,
                    "Tax1": 10,
                    "Tax2": 90,
                    "Tax3": 0,
                    "Tax4": 0,
                    "Tax5": 0,
                    "Tax6": 0,
                    "Tax7": 0,
                    "Tax8": 0,
                    "Tax9": 0,
                    "Parent": "99999997",
                    "VipLevel": 0,
                    "RakebackPercent": 0,
                    "killCount": 0,
                    "bounty": 0,
                    "bonus": 0
                },
                "tableScore": 0,
                "totalScore": 0,
                "isPlaying": false,
                "isGiveUp": false,
                "isAllIn": false,
                "pos": 1,
                "take": 3,
                "status": 3,
                "cards": [],
                "cardType": 0,
                "operateCard": 0,
                "maxCards": [],
                "isHaveCards": true,
                "showCards": [
                    0,
                    0
                ],
                "delayTimes": 0,
                "straddleNextCnt": -1,
                "isLeave": false,
                "isFocus": false,
                "isOpenMic": false,
                "turnLeftSeconds": 0,
                "mttUseDelay": false,
                "mttDelaySecond": 0,
                "nlhDelaySpend": 0,
                "payForGetCardType": 0,
                "squidCount": 0,
                "minTake": 0,
                "maxTake": 0,
                "isOriginTake": false,
                "handPlayerTurnedFlag": false,
                "nextGameLeaveFlag": false,
                "foldToStandUpFlag": false
            },
            {
                "userInfo": {
                    "comId": "JOY",
                    "userId": "1725962",
                    "userName": "+852 343663",
                    "nickname": "aa152",
                    "gender": 2,
                    "signiture": "",
                    "photoUrl": "4",
                    "ip": "172.71.8.45",
                    "jingDu": 200,
                    "weiDu": 200,
                    "score": 2029,
                    "idType": 0,
                    "isOpenMic": false,
                    "matchInfo": {
                        "gameTimes": 0,
                        "playTimes": 0,
                        "vPIP": 0,
                        "winRate": 0
                    },
                    "poolRate": "50.00%",
                    "country": "",
                    "Level": 0,
                    "TaxSetting": 0,
                    "TaxDefault": 0,
                    "Uid0": "",
                    "Uid1": "",
                    "Uid2": "",
                    "Uid3": "",
                    "Uid4": "",
                    "Uid5": "",
                    "Uid6": "",
                    "Uid7": "",
                    "Uid8": "",
                    "Uid9": "",
                    "TaxSetting0": 0,
                    "TaxSetting1": 0,
                    "TaxSetting2": 0,
                    "TaxSetting3": 0,
                    "TaxSetting4": 0,
                    "TaxSetting5": 0,
                    "TaxSetting6": 0,
                    "TaxSetting7": 0,
                    "TaxSetting8": 0,
                    "TaxSetting9": 0,
                    "Tax0": 0,
                    "Tax1": 0,
                    "Tax2": 0,
                    "Tax3": 0,
                    "Tax4": 0,
                    "Tax5": 0,
                    "Tax6": 0,
                    "Tax7": 0,
                    "Tax8": 0,
                    "Tax9": 0,
                    "Parent": "99999997",
                    "VipLevel": 0,
                    "RakebackPercent": 0,
                    "killCount": 0,
                    "bounty": 0,
                    "bonus": 0
                },
                "tableScore": 0,
                "totalScore": 0,
                "isPlaying": false,
                "isGiveUp": false,
                "isAllIn": false,
                "pos": 2,
                "take": 888,
                "status": 3,
                "cards": [],
                "cardType": 0,
                "operateCard": 0,
                "maxCards": [],
                "isHaveCards": true,
                "showCards": [
                    0,
                    0
                ],
                "delayTimes": 0,
                "straddleNextCnt": -1,
                "isLeave": false,
                "isFocus": false,
                "isOpenMic": false,
                "turnLeftSeconds": 0,
                "mttUseDelay": false,
                "mttDelaySecond": 0,
                "nlhDelaySpend": 0,
                "payForGetCardType": 0,
                "squidCount": 0,
                "minTake": 0,
                "maxTake": 0,
                "isOriginTake": false,
                "handPlayerTurnedFlag": false,
                "nextGameLeaveFlag": false,
                "foldToStandUpFlag": false
            },
            {
                "userInfo": {
                    "comId": "JOY",
                    "userId": "1725970",
                    "userName": "+852 320041",
                    "nickname": "aa153",
                    "gender": 2,
                    "signiture": "",
                    "photoUrl": "0",
                    "ip": "172.70.223.233",
                    "jingDu": 200,
                    "weiDu": 200,
                    "score": 891,
                    "idType": 0,
                    "isOpenMic": false,
                    "matchInfo": {
                        "gameTimes": 0,
                        "playTimes": 0,
                        "vPIP": 0,
                        "winRate": 0
                    },
                    "poolRate": "47.50%",
                    "country": "",
                    "Level": 0,
                    "TaxSetting": 0,
                    "TaxDefault": 0,
                    "Uid0": "",
                    "Uid1": "",
                    "Uid2": "",
                    "Uid3": "",
                    "Uid4": "",
                    "Uid5": "",
                    "Uid6": "",
                    "Uid7": "",
                    "Uid8": "",
                    "Uid9": "",
                    "TaxSetting0": 0,
                    "TaxSetting1": 0,
                    "TaxSetting2": 0,
                    "TaxSetting3": 0,
                    "TaxSetting4": 0,
                    "TaxSetting5": 0,
                    "TaxSetting6": 0,
                    "TaxSetting7": 0,
                    "TaxSetting8": 0,
                    "TaxSetting9": 0,
                    "Tax0": 0,
                    "Tax1": 0,
                    "Tax2": 0,
                    "Tax3": 0,
                    "Tax4": 0,
                    "Tax5": 0,
                    "Tax6": 0,
                    "Tax7": 0,
                    "Tax8": 0,
                    "Tax9": 0,
                    "Parent": "99999997",
                    "VipLevel": 0,
                    "RakebackPercent": 0,
                    "killCount": 0,
                    "bounty": 0,
                    "bonus": 0
                },
                "tableScore": 0,
                "totalScore": 0,
                "isPlaying": false,
                "isGiveUp": false,
                "isAllIn": false,
                "pos": 3,
                "take": 888,
                "status": 3,
                "cards": [],
                "cardType": 0,
                "operateCard": 0,
                "maxCards": [],
                "isHaveCards": true,
                "showCards": [
                    0,
                    0
                ],
                "delayTimes": 0,
                "straddleNextCnt": -1,
                "isLeave": false,
                "isFocus": false,
                "isOpenMic": false,
                "turnLeftSeconds": 0,
                "mttUseDelay": false,
                "mttDelaySecond": 0,
                "nlhDelaySpend": 0,
                "payForGetCardType": 0,
                "squidCount": 0,
                "minTake": 0,
                "maxTake": 0,
                "isOriginTake": false,
                "handPlayerTurnedFlag": false,
                "nextGameLeaveFlag": false,
                "foldToStandUpFlag": false
            },
            {
                "userInfo": {
                    "comId": "JOY",
                    "userId": "1728234",
                    "userName": "+852 563048",
                    "nickname": "aa435",
                    "gender": 1,
                    "signiture": "",
                    "photoUrl": "5",
                    "ip": "162.158.119.63",
                    "jingDu": 200,
                    "weiDu": 200,
                    "score": 719.5,
                    "idType": 0,
                    "isOpenMic": false,
                    "matchInfo": {
                        "gameTimes": 0,
                        "playTimes": 0,
                        "vPIP": 0,
                        "winRate": 0
                    },
                    "poolRate": "54.72%",
                    "country": "",
                    "Level": 9,
                    "TaxSetting": 0,
                    "TaxDefault": 0,
                    "Uid0": "99999999",
                    "Uid1": "99999998",
                    "Uid2": "99999997",
                    "Uid3": "",
                    "Uid4": "",
                    "Uid5": "",
                    "Uid6": "",
                    "Uid7": "",
                    "Uid8": "",
                    "Uid9": "",
                    "TaxSetting0": 100,
                    "TaxSetting1": 100,
                    "TaxSetting2": 90,
                    "TaxSetting3": 0,
                    "TaxSetting4": 0,
                    "TaxSetting5": 0,
                    "TaxSetting6": 0,
                    "TaxSetting7": 0,
                    "TaxSetting8": 0,
                    "TaxSetting9": 0,
                    "Tax0": 0,
                    "Tax1": 10,
                    "Tax2": 90,
                    "Tax3": 0,
                    "Tax4": 0,
                    "Tax5": 0,
                    "Tax6": 0,
                    "Tax7": 0,
                    "Tax8": 0,
                    "Tax9": 0,
                    "Parent": "99999997",
                    "VipLevel": 0,
                    "RakebackPercent": 0,
                    "killCount": 0,
                    "bounty": 0,
                    "bonus": 0
                },
                "tableScore": 0,
                "totalScore": 0,
                "isPlaying": false,
                "isGiveUp": false,
                "isAllIn": false,
                "pos": 4,
                "take": 888,
                "status": 3,
                "cards": [],
                "cardType": 0,
                "operateCard": 0,
                "maxCards": [],
                "isHaveCards": true,
                "showCards": [
                    0,
                    0
                ],
                "delayTimes": 0,
                "straddleNextCnt": -1,
                "isLeave": false,
                "isFocus": false,
                "isOpenMic": false,
                "turnLeftSeconds": 0,
                "mttUseDelay": false,
                "mttDelaySecond": 0,
                "nlhDelaySpend": 0,
                "payForGetCardType": 0,
                "squidCount": 0,
                "minTake": 0,
                "maxTake": 0,
                "isOriginTake": false,
                "handPlayerTurnedFlag": false,
                "nextGameLeaveFlag": false,
                "foldToStandUpFlag": false
            },
            {
                "userInfo": {
                    "comId": "JOY",
                    "userId": "1728242",
                    "userName": "+852 766556",
                    "nickname": "aa436",
                    "gender": 2,
                    "signiture": "",
                    "photoUrl": "2",
                    "ip": "172.71.8.45",
                    "jingDu": 200,
                    "weiDu": 200,
                    "score": 250.5,
                    "idType": 0,
                    "isOpenMic": false,
                    "matchInfo": {
                        "gameTimes": 0,
                        "playTimes": 0,
                        "vPIP": 0,
                        "winRate": 0
                    },
                    "poolRate": "43.64%",
                    "country": "",
                    "Level": 9,
                    "TaxSetting": 0,
                    "TaxDefault": 0,
                    "Uid0": "99999999",
                    "Uid1": "99999998",
                    "Uid2": "99999997",
                    "Uid3": "",
                    "Uid4": "",
                    "Uid5": "",
                    "Uid6": "",
                    "Uid7": "",
                    "Uid8": "",
                    "Uid9": "",
                    "TaxSetting0": 100,
                    "TaxSetting1": 100,
                    "TaxSetting2": 90,
                    "TaxSetting3": 0,
                    "TaxSetting4": 0,
                    "TaxSetting5": 0,
                    "TaxSetting6": 0,
                    "TaxSetting7": 0,
                    "TaxSetting8": 0,
                    "TaxSetting9": 0,
                    "Tax0": 0,
                    "Tax1": 10,
                    "Tax2": 90,
                    "Tax3": 0,
                    "Tax4": 0,
                    "Tax5": 0,
                    "Tax6": 0,
                    "Tax7": 0,
                    "Tax8": 0,
                    "Tax9": 0,
                    "Parent": "99999997",
                    "VipLevel": 0,
                    "RakebackPercent": 0,
                    "killCount": 0,
                    "bounty": 0,
                    "bonus": 0
                },
                "tableScore": 0,
                "totalScore": 0,
                "isPlaying": false,
                "isGiveUp": false,
                "isAllIn": false,
                "pos": 5,
                "take": 888,
                "status": 3,
                "cards": [],
                "cardType": 0,
                "operateCard": 0,
                "maxCards": [],
                "isHaveCards": true,
                "showCards": [
                    0,
                    0
                ],
                "delayTimes": 0,
                "straddleNextCnt": -1,
                "isLeave": false,
                "isFocus": false,
                "isOpenMic": false,
                "turnLeftSeconds": 0,
                "mttUseDelay": false,
                "mttDelaySecond": 0,
                "nlhDelaySpend": 0,
                "payForGetCardType": 0,
                "squidCount": 0,
                "minTake": 0,
                "maxTake": 0,
                "isOriginTake": false,
                "handPlayerTurnedFlag": false,
                "nextGameLeaveFlag": false,
                "foldToStandUpFlag": false
            }
        ],
        "basePool": 0,
        "poolInfos": null,
        "curTurnUserId": "",
        "curTurnTime": 1746589920,
        "lastEndTime": 1746589920,
        "leftTime": 14,
        "leftTimeStamp": 1746589935,
        "centerCards": null,
        "dUserId": "1725970",
        "sUserId": "1728234",
        "bUserId": "1728242",
        "callCount": 0,
        "isAllIn": false,
        "isGameResult": false,
        "commandId": 4175,
        "isCanDelay": false,
        "leftDelayCount": 0,
        "delaySpend": 0,
        "raiseCount": 0,
        "totalTime": 0,
        "straddleUsers": [],
        "inSureUsers": null,
        "inSurePools": null,
        "winRates": null,
        "livingUserId": "",
        "anchorPhotoUrl": "",
        "anchorNickName": "",
        "delayTimes": 0,
        "isInvalidRaise": false,
        "gt": 1,
        "dUserPos": 3,
        "isGameStart": false,
        "maxRaise": 0,
        "minCall": 0,
        "initPool": 0,
        "gameSenceStatus": 2
    },
    "giftInfo": null,
    "roomType": 3,
    "anchorSettingValue": {},
    "disableMicphoneUsers": null,
    "closeMicphoneUsers": null,
    "disableAllDefaultUsers": [
        "1725970",
        "1736186",
        "1725274",
        "1736218",
        "1730992",
        "1731080",
        "1736178",
        "1736194",
        "1736202",
        "1739162",
        "1725282",
        "1731072",
        "1736210",
        "1739154",
        "1725962",
        "1728234",
        "1728242",
        "1730984"
    ],
    "liverId": "",
    "liverNickName": "",
    "liverPhotoUrl": "",
    "isAnchorInRoom": false,
    "clubId": 0,
    "ownerIsStart": true,
    "isOnceLived": false,
    "raisCount": 0,
    "dismissLeftTime": 0,
    "dismissLeftTimeStamp": 0,
    "userId": "1731072",
    "timeToSeeCards": 2,
    "autoPlayStatus": "",
    "vpipLimit": 0
}